=== Lamoth08/ServiceMessagerie/Modélisation/messagerie.dtd
<!ELEMENT serviceMessagerie (utilisateurs)>

<!ELEMENT utilisateurs (utilisateur+)>

<!ELEMENT utilisateur (contacts, discussions, appels)>
<!ATTLIST utilisateur
    id ID #REQUIRED
    nom CDATA #REQUIRED
    numero CDATA #REQUIRED
    statut (Offline | Online) #REQUIRED>


<!ELEMENT contacts (contact*)>

<!ELEMENT contact (photo?, Groupes*)>
<!ATTLIST contact
    id ID #REQUIRED
    nom CDATA #REQUIRED
    numero CDATA #REQUIRED
    statut (Offline | Online) #REQUIRED
>

<!ELEMENT photo (#PCDATA)>

<!ELEMENT Groupes (Groupe+)>

<!ELEMENT Groupe EMPTY>
<!ATTLIST Groupe id IDREF #REQUIRED>


<!ELEMENT discussions (discussion*)>

<!ELEMENT discussion (correspondant?,infoGroupe?, messages)>
<!ATTLIST discussion
    categorie (individuelle | groupe) #REQUIRED
    id ID #REQUIRED
>

<!ELEMENT correspondant EMPTY>
<!ATTLIST correspondant id IDREF #REQUIRED
>

<!ELEMENT infoGroupe (membres)>
<!ATTLIST infoGroupe
    id ID #REQUIRED
    nom CDATA #REQUIRED
    description CDATA #REQUIRED
    nombreMembres CDATA #REQUIRED
>
<!ELEMENT membres (membre*)>

<!ELEMENT membre EMPTY>
<!ATTLIST membre id IDREF #REQUIRED>

<!ELEMENT messages (message*)>

<!ELEMENT message (contenu, citation?)>
<!ATTLIST message
    id ID #REQUIRED
    expediteur IDREF #REQUIRED
    type CDATA #REQUIRED
    timestamp CDATA #REQUIRED
>

<!ELEMENT contenu (texte?, fichier?, vocal?)>

<!ELEMENT texte (#PCDATA)>
<!ELEMENT fichier (#PCDATA)>
<!ELEMENT vocal EMPTY>
<!ATTLIST vocal
    minutes CDATA #REQUIRED
    secondes CDATA #REQUIRED
>

<!ELEMENT citation EMPTY>
<!ATTLIST citation message IDREF #REQUIRED
>

<!ELEMENT appels (appel*)>

<!ELEMENT appel (correspondant?,membres?, duree)>
<!ATTLIST appel
    type CDATA #REQUIRED
    categorie CDATA #REQUIRED
    chiffre (true | false) #REQUIRED
>


<!ELEMENT duree EMPTY>
<!ATTLIST duree
    heures CDATA #REQUIRED
    minutes CDATA #REQUIRED
>

<!ELEMENT chiffre (#PCDATA)>

=== Lamoth08/ServiceMessagerie/Modélisation/serviceMessagerie.xml
<?xml version="1.0" encoding="UTF-8"?>
<serviceMessagerie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="messagerie.xsd">

<!--<!DOCTYPE serviceMessagerie SYSTEM "messagerie.dtd">--> 

    <utilisateurs> 
        <utilisateur id="u1" nom="Lamoth Mboup" numero="7711122" statut="Online">
            <contacts>
                <contact id="c1" nom="Oumar" numero="7745098" statut="Online">
                  <photo>oumar.jpg</photo>
                  <Groupes>
                    <Groupe id="g1"/>
                    <Groupe id="g2"/>
                  </Groupes>
                </contact>
                <contact id="c2" nom="Seynabou" numero="7654345" statut="Offline">
                  <photo>seynabou.jpg</photo>
                </contact>
                <contact id="c3" nom="Rokhaya" numero="7567789" statut="Online">
                  <photo>rokhaya.jpg</photo>
                </contact>
                <contact id="c4" nom="Fama" numero="7737401" statut="Offline">
                  <photo>fama.jpg</photo>
                </contact>
            </contacts>

            <discussions>
                <discussion categorie="individuelle" id="d1">
                    <correspondant id="c3"/>
                    <messages>
                        <message id="m1" expediteur="c3" type="texte" timestamp="2023-06-26T10:00:00">
                            <contenu>
                                <texte>Salut comment vas-tu??</texte>    
                            </contenu>
                        </message>
                        <message id="m2" expediteur="u1" type="texte" timestamp="2023-06-26T10:05:00">
                            <contenu>
                                <texte>Bien et toi?</texte>
                            </contenu>
                            <citation message="m1"/>
                        </message>
                    </messages>
                </discussion>

                <discussion categorie="individuelle" id="d2">
                    <correspondant id="u2"/>
                    <messages>
                        <message id="m3" expediteur="u2" type="texte" timestamp="2023-06-26T10:00:00">
                            <contenu>
                                <texte>Bonjour tu n'as pas oublie notre reunion.</texte>   
                            </contenu>
                        </message>
                        <message id="m4" expediteur="u1" type="texte" timestamp="2023-06-26T10:10:00">
                            <contenu>
                                <texte>Non j'ai pas oublie</texte>
                            </contenu>
                        </message>
                        <message id="m5" expediteur="u2" type="vocal" timestamp="2023-06-26T10:10:00">
                            <contenu>
                               <vocal minutes="00" secondes="15" />
                            </contenu>
                            <citation message="m2"/>
                        </message>
                    </messages>
                </discussion>
                
                <discussion categorie="groupe" id="d3">
                    <infoGroupe id="g1" nom="les anciens de l'esp" description="ce groupe regroupe les alumnis de l'esp" nombreMembres="56">
                        <membres>
                            <membre id="u2" />
                            <membre id="c2" />
                            <membre id="c3"/>
                            <membre id="c4"/>
                        </membres>
                    </infoGroupe>
    
                    <messages>
                        <message id="m6" expediteur="c4" type="texte" timestamp="2023-06-27T11:00:00">
                            <contenu>
                                <texte>Salut, quelqu'un pour m'envoyer le projet de xml</texte>
                            </contenu>
                        </message>
                        <message id="m7" expediteur="c3" type="fichier" timestamp="2023-06-2T11:10:00">
                            <contenu>
                                <fichier>/home/lamoth/Bureau/projetxml.pdf</fichier>
                            </contenu>
                            <citation message="m1"/>
                        </message>
                    </messages>
                </discussion>

                <discussion categorie="groupe" id="d4">
                    <infoGroupe id="g2" nom="otakus" description="manga life" nombreMembres="6">
                        <membres>
                            <membre id="u2" />
                            <membre id="c2" />
                            <membre id="c3"/>
                            <membre id="c4"/>
                        </membres>
                    </infoGroupe>
                    <messages></messages>
                </discussion>
            </discussions>
            <appels>
                <appel type="vocal" categorie="groupe" chiffre="true">
                    <membres>
                        <membre id="u2" />
                        <membre id="c2" />
                        <membre id="c3"/>
                        <membre id="c4"/>
                    </membres>
                    <duree heures="00" minutes="15" />
                </appel>
                <appel type="vocal" categorie="individuelle" chiffre="true">
                    <correspondant id="c2" />
                    <duree heures="00" minutes="15" />
                </appel>
                <appel type="video" categorie="groupe" chiffre="true">
                    <membres>
                        <membre id="u2" />
                        <membre id="c2" />
                        <membre id="c3"/>
                        <membre id="c4"/>
                    </membres>
                    <duree heures="01" minutes="15" />
                </appel>
                <appel type="video" categorie="individuelle" chiffre="true">
                    <correspondant id="c3" />
                    <duree heures="00" minutes="15" />
                </appel>
            </appels>
        </utilisateur>
        
        <utilisateur id="u2" nom="Utilisateur 2" numero="7722334" statut="Offline">
            <contacts>
                <contact id="c5" nom="Aliou" numero="7890123" statut="Online">
                  <photo>aliou.jpg</photo>
                  <Groupes>
                    <Groupe id="g3"/>
                    <Groupe id="g4"/>
                  </Groupes>
                </contact>
                <contact id="c6" nom="Aissatou" numero="7012345" statut="Online">
                  <photo>aissatou.jpg</photo>
                </contact>
            </contacts>
            <discussions>
                <discussion categorie="individuelle" id="d5">
                    <correspondant id="c5"/>
                    <messages>
                        <message id="m8" expediteur="c5" type="texte" timestamp="2023-06-27T10:00:00">
                            <contenu>
                                <texte>Bonjour, comment ça va?</texte>    
                            </contenu>
                        </message>
                        <message id="m9" expediteur="u2" type="texte" timestamp="2023-06-27T10:05:00">
                            <contenu>
                                <texte>Ça va bien, merci!</texte>
                            </contenu>
                            <citation message="m8"/>
                        </message>
                    </messages>
                </discussion>
                <discussion categorie="groupe" id="d6">
                    <infoGroupe id="g3" nom="Collègues" description="Groupe des collègues de travail" nombreMembres="12">
                        <membres>
                            <membre id="u2" />
                            <membre id="c5" />
                            <membre id="c6"/>
                        </membres>
                    </infoGroupe>
    
                    <messages>
                        <message id="m10" expediteur="c6" type="texte" timestamp="2023-06-28T11:00:00">
                            <contenu>
                                <texte>Bonne nouvelle, notre projet a été accepté!</texte>
                            </contenu>
                        </message>
                    </messages>
                </discussion>

                <discussion categorie="groupe" id="d7">
                    <infoGroupe id="g4" nom="Amis" description="Groupe des amis proches" nombreMembres="5">
                        <membres>
                            <membre id="u2" />
                            <membre id="c5" />
                            <membre id="c6"/>
                        </membres>
                    </infoGroupe>
                    <messages></messages>
                </discussion>
            </discussions>
            <appels>
                <appel type="vocal" categorie="groupe" chiffre="true">
                    <membres>
                        <membre id="u2" />
                        <membre id="c5" />
                        <membre id="c6"/>
                    </membres>
                    <duree heures="00" minutes="20" />
                </appel>
                <appel type="video" categorie="groupe" chiffre="true">
                    <membres>
                        <membre id="u2" />
                        <membre id="c5" />
                        <membre id="c6"/>
                    </membres>
                    <duree heures="01" minutes="30" />
                </appel>
            </appels>
        </utilisateur>
    </utilisateurs>
</serviceMessagerie>
